### ISSUE TITLE
NVDA 2023.1 compatibility

### ISSUE THREAD

**Issue by marlon-sousa** [mltony/nvda-console-toolkit#5]
Hello,

Inspecting master it seems that NVDA 2023.1 compatibility is already implemented.

However, there is no aassociated release in the release page.

Can you confirm if we can use master to build the addon offline or if something else is needed to release the compatible version?

**Comment by blindndangerous** [comment]
Did you get anywhere with this?  I'd really like to be able to use this again.

**Comment by cary-rowen** [comment]
cc @mltony 
Version 1.4 is already available in the store and we can close this.

**Comment by mltony** [comment]
Right, it should be compatible now. I'll close this - but feel free to reopen if still any problems.
